name: Release (Release Please)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - name: Create Release PR or Release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
      # The logic below handles the bun publication:
      - uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
        if: ${{ steps.release.outputs.release_created }}
      - run: bun install --frozen-lockfile
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish to npm
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun publish -p --access public
        if: ${{ steps.release.outputs.release_created }}
